version: "3"
services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis/redis.conf:/etc/redis/redis_default.conf
      - ./redis/data/:/data
    environment:
      TZ: "Asia/Shanghai"
    command: redis-server /etc/redis/redis_default.conf --appendonly yes
  ivp:
    build:
      context: ivp
      args:
        gitUrl: "https://github.com/RongLiXu"
        zlmGitUrl: "https://gitee.com/xia-chu/ZLMediaKit"
    restart: always
    ports:
      - "80:80"
      - "554:554"
      - "1935:1935"
      - "5060:5060"
      - "5060:5060/udp"
      - "18080:18080"
      - "18081:18081"
      - "10000:10000/tcp"
      - "10000:10000/udp"
      - "30000-30500:30000-30500/tcp"
      - "30000-30500:30000-30500/udp"
    volumes:
      - ./video:/opt/media/www/record
      - ./logs/wvp:/opt/wvp/logs/
      - ./logs/assist:/opt/assist/logs/
      - ./logs/media:/opt/media/log/
    environment:
      TZ: "Asia/Shanghai"
      # [必须修改] 本机的IP
      IVP_HOST: 172.18.0.61
      IVP_PWD: aseqw_+hiy123
      IVP_DOMAIN: 6101130049
      IVP_ID: 61011300490000000001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 6
      REDIS_PWD: root
      ASSIST_JVM_CONFIG: -Xms128m -Xmx256m
      IVP_JVM_CONFIG: -Xms128m -Xmx256m
      ASSIST_CONFIG:
      IVP_CONFIG:
    depends_on:
      - redis
